2024-10-21 18:29:16 / WARNING: / Неверная скорость для Runner: Скорость не может быть отрицательной, сейчас -5
Traceback (most recent call last):
  File "C:\Users\Andrey\PycharmProjects\FirstPythonProject\Python files\homeworks\tests_12_4.py", line 73, in test_walk
    r1 = Runner('Вася', -5)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\PycharmProjects\FirstPythonProject\Python files\homeworks\tests_12_4.py", line 23, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-10-21 18:29:16 / WARNING: / Неверный тип данных для объекта Runner: Имя может быть только строкой, передано int
Traceback (most recent call last):
  File "C:\Users\Andrey\PycharmProjects\FirstPythonProject\Python files\homeworks\tests_12_4.py", line 81, in test_run
    r2 = Runner(2, 10)
         ^^^^^^^^^^^^^
  File "C:\Users\Andrey\PycharmProjects\FirstPythonProject\Python files\homeworks\tests_12_4.py", line 18, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
